# Generated by Django 6.0.6 on 2026-06-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
    ]
